### ISSUE TITLE
Use eslint

### ISSUE THREAD

**Issue by GrosSacASac** [GrosSacASac/randomsac#2]
Use eslint with [JavaScript Red Style Guide](https://github.com/GrosSacASac/JavaScript-Set-Up/tree/master/js/red-javascript-style-guide)

**Comment by agawish** [comment]
I can help with that one.

Do you want to fix `eslint` problems -if any- as part of this PR?

**Comment by GrosSacASac** [comment]
It would be even better but not necessary, the minimum requirement it to have it set up

**Comment by agawish** [comment]
Great, thanks 👍 I'm working on it
